
import { User, Role, Department, Task, TaskPriority, TaskStatus, JobType, ColorMode, WorkflowStage, Company, SubscriptionPlan } from './types';

// MOCK COMPANIES
export const COMPANIES: Company[] = [
    { 
        id: 'c1', 
        name: 'PrintFlow Global', 
        status: 'Active', 
        subscription: { plan: SubscriptionPlan.Enterprise, startDate: new Date('2023-01-01'), status: 'Active' },
        createdAt: new Date('2023-01-01') 
    },
    { 
        id: 'c2', 
        name: 'Acme Printing Co.', 
        status: 'Active', 
        subscription: { plan: SubscriptionPlan.Pro, startDate: new Date('2024-02-15'), status: 'Active' },
        createdAt: new Date('2024-02-15') 
    },
    { 
        id: 'c3', 
        name: 'FastTrack Graphics', 
        status: 'Pending', 
        subscription: { plan: SubscriptionPlan.Basic, startDate: new Date('2025-03-10'), status: 'Active' },
        createdAt: new Date('2025-03-10') 
    },
];

// MOCK USERS
export const USERS: User[] = [
  { id: 'm1', fullName: 'Super Admin', email: 'master@printflow.com', mobile: '000-000-0000', role: Role.SuperAdmin, department: Department.Management, avatar: 'https://i.pravatar.cc/150?u=m1', companyId: 'c1', companyName: 'PrintFlow Global' },
  { id: 'u1', fullName: 'Admin User', email: 'admin@printflow.com', mobile: '111-222-3333', role: Role.CompanyAdmin, department: Department.Management, avatar: 'https://i.pravatar.cc/150?u=u1', companyId: 'c2', companyName: 'Acme Printing Co.' },
  { id: 'u2', fullName: 'Manager Mike', email: 'mike.m@printflow.com', mobile: '222-333-4444', role: Role.Manager, department: Department.Management, avatar: 'https://i.pravatar.cc/150?u=u2', companyId: 'c2', companyName: 'Acme Printing Co.' },
  { id: 'u3', fullName: 'Emily Press', email: 'emily.p@printflow.com', mobile: '333-444-5555', role: Role.Operator, department: Department.Press, avatar: 'https://i.pravatar.cc/150?u=u3', companyId: 'c2', companyName: 'Acme Printing Co.' },
  { id: 'u4', fullName: 'David Design', email: 'david.d@printflow.com', mobile: '444-555-6666', role: Role.Operator, department: Department.PrePress, avatar: 'https://i.pravatar.cc/150?u=u4', companyId: 'c2', companyName: 'Acme Printing Co.' },
  { id: 'u5', fullName: 'Sarah Finish', email: 'sarah.f@printflow.com', mobile: '555-666-7777', role: Role.Operator, department: Department.PostPress, avatar: 'https://i.pravatar.cc/150?u=u5', companyId: 'c2', companyName: 'Acme Printing Co.' },
];

// MOCK TASKS
export const TASKS: Task[] = [
  {
    id: 't1',
    companyId: 'c2',
    title: 'Brochure Design Proofing for "Sunrise Cafe"',
    description: 'Final check on the new tri-fold brochure design. Verify colors, text, and layout against the client brief.',
    priority: TaskPriority.High,
    status: TaskStatus.New,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    createdAt: new Date(new Date().setDate(new Date().getDate() - 2)),
    estimatedHours: 4,
    assignedTo: ['u4'],
    createdBy: 'u2',
    workflowStage: WorkflowStage.PrePress,
    printingDetails: {
      jobType: JobType.Digital,
      paperType: '150gsm Art Paper',
      gsm: 150,
      colorMode: ColorMode.CMYK,
      numberOfPages: 2,
      plateCount: 0,
      machineName: 'HP Indigo 7900',
      finishing: ['Gloss Lamination', 'Folding'],
      jobTicketNumber: 'JT-2024-001',
      proofRequired: true,
      artworkVersion: 'v2.1',
    },
    attachments: [{ id: 'a1', name: 'sunrise_brochure_v2.1.ai', url: '#', type: 'ai', uploadedAt: new Date(), version: 2.1 }],
    comments: [
        { id: 'c1', userId: 'u2', content: 'Please prioritize this. Client is on a tight deadline.', createdAt: new Date(new Date().setDate(new Date().getDate() - 1)) },
        { id: 'c2', userId: 'u4', content: 'Acknowledged. I will get on this right away.', createdAt: new Date() },
    ],
    activityLog: [{ id: 'ac1', userId: 'u2', action: 'Created task and assigned to David Design', timestamp: new Date() }],
  },
  {
    id: 't2',
    companyId: 'c2',
    title: 'Offset Printing Run for "TechCorp" Annual Report',
    description: '10,000 copies of the 48-page annual report. Machine setup and color calibration required.',
    priority: TaskPriority.Urgent,
    status: TaskStatus.InProgress,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    createdAt: new Date(new Date().setDate(new Date().getDate() - 5)),
    estimatedHours: 16,
    assignedTo: ['u3'],
    createdBy: 'u2',
    workflowStage: WorkflowStage.Press,
    printingDetails: {
      jobType: JobType.Offset,
      paperType: '100gsm Matte Coated',
      gsm: 100,
      colorMode: ColorMode.CMYK,
      numberOfPages: 48,
      plateCount: 12,
      machineName: 'Heidelberg Speedmaster XL 106',
      finishing: ['Perfect Binding', 'Matte Lamination on Cover'],
      jobTicketNumber: 'JT-2024-002',
      proofRequired: false,
      artworkVersion: 'vFinal',
    },
    attachments: [{ id: 'a2', name: 'techcorp_annual_report.pdf', url: '#', type: 'pdf', uploadedAt: new Date(), version: 1 }],
    comments: [
        { id: 'c3', userId: 'u3', content: 'Paper stock confirmed. Starting the machine setup now.', createdAt: new Date(new Date().setDate(new Date().getDate() - 3)) }
    ],
    activityLog: [
        { id: 'ac2', userId: 'u2', action: 'Created task and assigned to Emily Press', timestamp: new Date(new Date().setDate(new Date().getDate() - 5)) },
        { id: 'ac3', userId: 'u3', action: 'Accepted task', timestamp: new Date(new Date().setDate(new Date().getDate() - 4)) },
        { id: 'ac4', userId: 'u3', action: 'Changed status to In Progress', timestamp: new Date(new Date().setDate(new Date().getDate() - 3)) },
    ],
  },
  {
    id: 't3',
    companyId: 'c2',
    title: 'Business Card Cutting & Boxing for "Innovate Inc."',
    description: 'Guillotine cutting for 50 boxes of business cards. Ensure clean cuts and accurate dimensions.',
    priority: TaskPriority.Medium,
    status: TaskStatus.AwaitingApproval,
    dueDate: new Date(new Date().setDate(new Date().getDate() - 1)),
    createdAt: new Date(new Date().setDate(new Date().getDate() - 7)),
    estimatedHours: 3,
    actualHours: 2.5,
    assignedTo: ['u5'],
    createdBy: 'u2',
    workflowStage: WorkflowStage.PostPress,
    printingDetails: {
      jobType: JobType.Digital,
      paperType: '350gsm Silk Card',
      gsm: 350,
      colorMode: ColorMode.CMYK,
      numberOfPages: 2,
      plateCount: 0,
      machineName: 'Polar 115 Guillotine',
      finishing: ['Cutting', 'Boxing'],
      jobTicketNumber: 'JT-2024-003',
      proofRequired: false,
      artworkVersion: 'v1',
    },
    attachments: [],
    comments: [{ id: 'c4', userId: 'u5', content: 'Job is complete. Ready for final QC and manager approval.', createdAt: new Date() }],
    activityLog: [{ id: 'ac5', userId: 'u5', action: 'Marked as Done – Waiting for Approval', timestamp: new Date() }],
  },
  {
    id: 't4',
    companyId: 'c2',
    title: 'Flexo Label Printing for "Organic Goods"',
    description: 'Run of 50,000 product labels. Mix inks for spot colors accurately.',
    priority: TaskPriority.High,
    status: TaskStatus.Done,
    dueDate: new Date(new Date().setDate(new Date().getDate() - 10)),
    createdAt: new Date(new Date().setDate(new Date().getDate() - 15)),
    estimatedHours: 8,
    actualHours: 7.5,
    assignedTo: ['u3'],
    createdBy: 'u2',
    workflowStage: WorkflowStage.PostPress,
    printingDetails: {
      jobType: JobType.Flexo,
      paperType: 'Self-Adhesive Vinyl',
      gsm: 80,
      colorMode: ColorMode.Spot,
      numberOfPages: 1,
      plateCount: 4,
      machineName: 'Mark Andy P5',
      finishing: ['Die Cutting', 'Roll Winding'],
      jobTicketNumber: 'JT-2024-004',
      proofRequired: true,
      artworkVersion: 'v3',
    },
    attachments: [],
    comments: [],
    activityLog: [{ id: 'ac6', userId: 'u2', action: 'Approved and closed task.', timestamp: new Date(new Date().setDate(new Date().getDate() - 9)) }],
  },
   {
    id: 't5',
    companyId: 'c2',
    title: 'Screen Print T-Shirts for "Local Fest 2024"',
    description: '100 T-shirts with 2-color front print. Check screen tension and emulsion quality.',
    priority: TaskPriority.Low,
    status: TaskStatus.OnHold,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 10)),
    createdAt: new Date(new Date().setDate(new Date().getDate() - 1)),
    estimatedHours: 6,
    assignedTo: ['u5'],
    createdBy: 'u2',
    workflowStage: WorkflowStage.Press,
    printingDetails: {
      jobType: JobType.Screen,
      paperType: 'N/A (Cotton T-Shirt)',
      gsm: 180,
      colorMode: ColorMode.Spot,
      numberOfPages: 1,
      plateCount: 2,
      machineName: 'M&R Gauntlet III',
      finishing: ['Curing', 'Folding', 'Bagging'],
      jobTicketNumber: 'JT-2024-005',
      proofRequired: true,
      artworkVersion: 'v1.2',
    },
    attachments: [{ id: 'a3', name: 'tshirt_design_v1.2.psd', url: '#', type: 'psd', uploadedAt: new Date(), version: 1.2 }],
    comments: [{ id: 'c5', userId: 'u2', content: 'Client has put the order on hold. Waiting for their confirmation to proceed.', createdAt: new Date() }],
    activityLog: [{ id: 'ac7', userId: 'u2', action: 'Changed status to On Hold', timestamp: new Date() }],
  },
  {
    id: 't6',
    companyId: 'c2',
    title: 'Client Artwork Correction',
    description: 'Client supplied artwork has low-res images. Need to contact them for better quality files.',
    priority: TaskPriority.High,
    status: TaskStatus.Rejected,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 2)),
    createdAt: new Date(new Date().setDate(new Date().getDate() - 1)),
    estimatedHours: 2,
    assignedTo: ['u4'],
    createdBy: 'u2',
    workflowStage: WorkflowStage.PrePress,
    printingDetails: {
      jobType: JobType.Digital,
      paperType: '170gsm Silk',
      gsm: 170,
      colorMode: ColorMode.CMYK,
      numberOfPages: 8,
      plateCount: 0,
      machineName: 'Xerox Iridesse',
      finishing: ['Saddle Stitching'],
      jobTicketNumber: 'JT-2024-006',
      proofRequired: true,
      artworkVersion: 'v1-client',
    },
    attachments: [],
    comments: [{ id: 'c6', userId: 'u2', content: 'The images are too pixelated. Sending back to you to get new files from the client.', createdAt: new Date() }],
    activityLog: [{ id: 'ac8', userId: 'u2', action: 'Rejected task. Awaiting new files.', timestamp: new Date() }],
  },
   {
    id: 't7',
    companyId: 'c2',
    title: 'Finalize quarterly sales presentation binder',
    description: 'Print and bind 20 copies of the Q3 sales presentation. Ensure cover is laminated and binding is secure.',
    priority: TaskPriority.Medium,
    status: TaskStatus.New,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 5)),
    createdAt: new Date(),
    estimatedHours: 5,
    assignedTo: ['u5'],
    createdBy: 'u2',
    workflowStage: WorkflowStage.PostPress,
    printingDetails: {
      jobType: JobType.Digital,
      paperType: '120gsm Uncoated, 300gsm cover',
      gsm: 120,
      colorMode: ColorMode.CMYK,
      numberOfPages: 30,
      plateCount: 0,
      machineName: 'HP Indigo 7900',
      finishing: ['Coil Binding', 'Matte Lamination on Cover'],
      jobTicketNumber: 'JT-2024-007',
      proofRequired: false,
      artworkVersion: 'v4',
    },
    attachments: [{ id: 'a4', name: 'q3_presentation.pdf', url: '#', type: 'pdf', uploadedAt: new Date(), version: 4 }],
    comments: [],
    activityLog: [{ id: 'ac9', userId: 'u2', action: 'Created task and assigned to Sarah Finish', timestamp: new Date() }],
  },
];